package com.highradius.cp;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.Scanner;  

/**
 @author debasish.mahana
 **/

public class sqlQueryHelper { 
	    @SuppressWarnings("resource")
		public static void main(String args[]) throws IOException{ 
	    	int count=1;
	    	String query,strLine,input_path,output_path=null;
	    	System.out.print("Enter File Name to Save : ");
	    	input_path="C:\\Users\\debasish.mahana\\Desktop\\SqlQueryHelper\\TD\\Bailey.txt";
	    	output_path="C:\\Users\\debasish.mahana\\Desktop\\SqlQueryHelper\\TD\\Output\\";
	    	BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(input_path)));
	    	BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(output_path+File.separator+new Scanner(System.in).next()+".sql")));
	    	
	    			while ((strLine = br.readLine()) != null)   {
	    				
	    				query=
	    				"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_Generation' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1 ), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
	    				"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_File_Transmission' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
	    				"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Payment_Parsing' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1),'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
	    				"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Bank_Transmission_Generation' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n"+
	    				
	    				"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_Generation' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'[*.*]',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
	    				"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_File_Transmission' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'[*.*]',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
	    				"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Payment_Parsing' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'[*.*]',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
	    				"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Bank_Transmission_Generation' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'[*.*]',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n";
	    				
	    				bw.write(query);
	    	    		//bw.newLine();
	    	    		System.out.println(strLine+" - "+count++);
	    			}
	    			br.close();
	    			bw.close();
	    	System.out.println("Query File Generated Successfully....");
	    }
}

//////////////////////////////////Rough Work //////////////////////////////////////

/*
query="INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_Generation' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1 ), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_File_Transmission' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Payment_Parsing' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1),'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n" + 
"INSERT IGNORE INTO process_definition_health_metric_config ( `fk_account_id`, `fk_process_type_id`, `fk_process_health_metric_id`, `fk_process_definition_id`, `java_class_name`, `is_lower_better`, `expected_value`, `is_relative`, `green_gte_value`, `red_lte_value`, `is_monitor_actively_flag`, `is_monitor_end_of_batch_flag`, `active_abs_time_interval`, `is_deleted`, `create_user`, `create_time`, `update_user`, `update_time`) VALUES ('"+strLine+"', (SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) ,(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Bank_Transmission_Generation' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), (SELECT `pk_process_definition_id` FROM process_definition WHERE `pool_short_name`='All Payment Pools' AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' LIMIT 1) LIMIT 1), 'All Payment Pools','0','1.00000000','0','0.00000000','23.59000000','1','1','900','0', 'debasish.mahana', NOW(), 'debasish.mahana', NOW());\r\n";
 */
/*
query="INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_Generation' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'*.*',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Output_File_Transmission' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'*.*',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Generic_Payment_Parsing' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'*.*',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n" + 
"INSERT IGNORE INTO `health_metric_addtl_config` (`fk_account_id`, `fk_process_definition_health_metric_config_id`, `is_deleted`, `config1`, `config2`, `config3`, `config4`, `config5`, `create_user`, `create_time`, `update_user`, `update_time`, `config6`) VALUES('"+strLine+"',(SELECT `pk_process_definition_health_metric_config_id` FROM `process_definition_health_metric_config` WHERE `fk_account_id`="+strLine+" AND `fk_process_type_id`=(SELECT `pk_process_type_id` FROM `process_type` WHERE `short_name`='Generic Health Monitoring' AND `fk_process_health_metric_id`=(SELECT `pk_process_health_metric_id` FROM `process_health_metric` WHERE `short_name`='Bank_Transmission_Generation' LIMIT 1) LIMIT 1) AND `java_class_name`='All Payment Pools' LIMIT 1),'0','1',NULL,NULL,'*.*',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL);\r\n";
*/
/*
query="INSERT IGNORE INTO scheduled_agent (processor, description, job_name, cron_expression, config, agent_number, fk_account_id, job_group, create_user, create_date, update_user, update_date, fk_cluster_group_id, supports_distributed_execution, wait_trigger_until_last_trigger_completed, generate_trigger_logs) VALUES('CommandCenterAgentProcessor','GenericProcessingHealthMetricAgent',NULL,'0 0/5 * * * ?','accountId="+strLine+"\\r\\nagentName=GenericProcessingHealthMetricAgent\\r\\nisParent=false','160','"+strLine+"',NULL,'debasish.mahana',NOW(),'debasish.mahana',NOW(),NULL,'0',NULL,NULL);\r\n";
*/	